name: Hello World
on: [push]
jobs:
  helloworld:
    runs-on: ubuntu-latest
    steps:
      - name: First HelloWorld
        run: echo "Welcome to github action's world!"
  helloworld-secondly:
    runs-on: ubuntu-latest
    needs: helloworld
    steps:
      - name: Secondly HelloWorld
        run: echo "Hello World - Secondly"
  helloworld-extend:
    runs-on: ubuntu-latest
    needs: [helloworld,helloworld-secondly]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test Message
        run: echo "This is test message!"
