name: Hello World
on: [push]
jobs:
  hw:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello!"
  helloworld:
    runs-on: ubuntu-latest
    steps:
      - name: First HelloWorld
        run: echo "Welcome to github action's world!"
  helloworld-secondly:
    runs-on: ubuntu-latest
    needs: helloworld
    steps:
      - name: Secondly HelloWorld
        run: echo "Hello World - Secondly"
  helloworld-extend:
    runs-on: ubuntu-latest
    needs: [helloworld,helloworld-secondly]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test Message
        run: echo "This is test message!"
  helloworld-advanced:
    runs-on: ubuntu-latest
    needs: [helloworld,hw]
    steps:
      - name: Advanced HelloWorld
        run: echo "Advanced Hello World!"
  hw01:
    runs-on: ubuntu-latest
    needs: [helloworld]
    steps:
      - name: Hello World!
        run: echo "Hello World!"
  hw02:
    runs-on: ubuntu-latest
    needs: [helloworld,hw01,helloworld-advanced]
    steps:
      - name: Hello World!
        run: echo "Hello World!"
  hw03:
    runs-on: ubuntu-latest
    needs: [helloworld,helloworld-extend]
    steps:
      - name: Hello World!
        run: echo "Hello World!"
  hw04:
    runs-on: ubuntu-latest
    needs: [hw,helloworld,hw01,hw02,hw03]
    steps:
      - name: Hello World!
        run: echo "Hello World!"
